/**
 * Generates an idempotent Supabase seed migration from the bundled dataset.
 *
 *   node scripts/generate-seed-sql.ts > supabase/migrations/<timestamp>_seed_terralens_atlas.sql
 *
 * Requires Node 22.18+ (type stripping). Safe to re-run against a database
 * that already contains some rows: locations and issues use ON CONFLICT DO
 * NOTHING, and child rows are only inserted for issues that have none yet.
 */
import { issueSeeds, locationSeeds } from "../src/data/seed/index.ts";

const q = (v: string | number | null | undefined): string =>
  v === null || v === undefined
    ? "NULL"
    : typeof v === "number"
      ? String(v)
      : `'${v.replace(/'/g, "''")}'`;

const out: string[] = [];
const push = (s: string) => out.push(s);

push("-- TerraLens atlas seed. Generated by scripts/generate-seed-sql.ts — do not edit by hand.");
push("-- Idempotent: existing locations, issues and their child rows are left untouched.\n");

push(
  "INSERT INTO public.locations (name, country, country_code, type, latitude, longitude, summary, featured) VALUES",
);
push(
  locationSeeds
    .map(
      (l) =>
        ` (${[q(l.name), q(l.country), q(l.countryCode), `${q(l.type)}::public.location_type`, l.lat, l.lng, q(l.summary), l.featured ? "true" : "false"].join(", ")})`,
    )
    .join(",\n"),
);
push("ON CONFLICT (name, country) DO NOTHING;\n");

const countryOf = new Map(locationSeeds.map((l) => [l.name, l.country]));

push("INSERT INTO public.issues (location_id, category_id, title, severity, summary, description)");
push(
  "SELECT l.id, c.id, v.title, v.severity::public.severity_level, v.summary, v.description FROM (VALUES",
);
push(
  issueSeeds
    .map(
      (i) =>
        ` (${[q(i.location), q(countryOf.get(i.location)), q(i.category), q(i.title), q(i.severity), q(i.summary), q(i.description)].join(", ")})`,
    )
    .join(",\n"),
);
push(") AS v(loc, country, cat, title, severity, summary, description)");
push("JOIN public.locations l ON l.name = v.loc AND l.country = v.country");
push("JOIN public.categories c ON c.slug = v.cat");
push("ON CONFLICT (title) DO NOTHING;\n");

function children(
  table: string,
  columns: string[],
  rows: (string | number | null | undefined)[][],
  casts: Record<string, string> = {},
) {
  if (!rows.length) return;
  const select = columns.map((c) => (casts[c] ? `v.${c}::${casts[c]}` : `v.${c}`)).join(", ");
  push(`INSERT INTO public.${table} (issue_id, ${columns.join(", ")})`);
  push(`SELECT i.id, ${select} FROM (VALUES`);
  push(rows.map((r) => ` (${r.map(q).join(", ")})`).join(",\n"));
  push(`) AS v(issue, ${columns.join(", ")})`);
  push("JOIN public.issues i ON i.title = v.issue");
  push(`WHERE NOT EXISTS (SELECT 1 FROM public.${table} t WHERE t.issue_id = i.id);\n`);
}

children(
  "causes",
  ["title", "description"],
  issueSeeds.flatMap((i) => i.causes.map(([t, d]) => [i.title, t, d])),
);
children(
  "impacts",
  ["title", "description"],
  issueSeeds.flatMap((i) => i.impacts.map(([t, d]) => [i.title, t, d])),
);
children(
  "solutions",
  ["title", "description", "expected_impact"],
  issueSeeds.flatMap((i) => i.solutions.map(([t, d, e]) => [i.title, t, d, e])),
);
children(
  "indicators",
  ["name", "value", "unit", "year", "description"],
  issueSeeds.flatMap((i) =>
    (i.indicators ?? []).map((x) => [i.title, x.name, x.value, x.unit, x.year, x.description]),
  ),
  { value: "text", unit: "text", year: "integer" },
);
children(
  "sources",
  ["title", "organization", "url", "publication_date"],
  issueSeeds.flatMap((i) => i.sources.map(([t, o, u, d]) => [i.title, t, o, u, d])),
  { publication_date: "date" },
);

// Source links in the original seed that no longer resolve (checked 2026-09-17).
// Rewrites them to match the bundled dataset.
const URL_CORRECTIONS: [
  oldUrl: string,
  title: string,
  organization: string,
  url: string,
  clearDate?: boolean,
][] = [
  [
    "https://www.who.int/publications/m/item/heatwaves-and-health-guidance-on-warning-system-development",
    "Heatwaves: health topic and heat-health warning guidance",
    "World Health Organization",
    "https://www.who.int/health-topics/heatwaves",
    true,
  ],
  [
    "https://www.wri.org/insights/cape-towns-water-crisis",
    "Cape Town drought: lessons for urban water security (publisher site)",
    "World Resources Institute",
    "https://www.wri.org/",
  ],
  [
    "https://inweh.unu.edu/the-states-of-desalination-and-brine-production-a-global-outlook/",
    "The State of Desalination and Brine Production: A Global Outlook",
    "UN University Institute for Water, Environment and Health",
    "https://inweh.unu.edu/",
  ],
  [
    "https://oceanservice.noaa.gov/hazards/sealevelrise/sealevelrise-tech-report.html",
    "Sea Level Rise Technical Report (NOAA sea level rise portal)",
    "NOAA / US Interagency Sea Level Rise Task Force",
    "https://oceanservice.noaa.gov/hazards/sealevelrise/",
  ],
  [
    "https://www.mse.gov.sg/resource-room/category/2019-08-29-zero-waste-masterplan/",
    "Zero Waste Masterplan",
    "Ministry of Sustainability and the Environment, Singapore",
    "https://www.mse.gov.sg/",
  ],
];
push("-- Corrections for source links that no longer resolve.");
for (const [oldUrl, title, org, url, clearDate] of URL_CORRECTIONS) {
  push(
    `UPDATE public.sources SET title = ${q(title)}, organization = ${q(org)}, url = ${q(url)}${clearDate ? ", publication_date = NULL" : ""} WHERE url = ${q(oldUrl)};`,
  );
}
push("");

process.stdout.write(out.join("\n"));
