/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as LocationsLocationIdRouteImport } from './routes/locations.$locationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdRoute = LocationsLocationIdRouteImport.update({
  id: '/locations/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/pulse': typeof PulseRoute
  '/what-if': typeof WhatIfRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/pulse': typeof PulseRoute
  '/what-if': typeof WhatIfRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/pulse': typeof PulseRoute
  '/what-if': typeof WhatIfRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/explore'
    | '/pulse'
    | '/what-if'
    | '/issues/$issueId'
    | '/locations/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/explore'
    | '/pulse'
    | '/what-if'
    | '/issues/$issueId'
    | '/locations/$locationId'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/explore'
    | '/pulse'
    | '/what-if'
    | '/issues/$issueId'
    | '/locations/$locationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ExploreRoute: typeof ExploreRoute
  PulseRoute: typeof PulseRoute
  WhatIfRoute: typeof WhatIfRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  LocationsLocationIdRoute: typeof LocationsLocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId': {
      id: '/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ExploreRoute: ExploreRoute,
  PulseRoute: PulseRoute,
  WhatIfRoute: WhatIfRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  LocationsLocationIdRoute: LocationsLocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
